version: "3.7"

volumes:
  pgdata:

services:
  maindb:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5.0.8-alpine
    restart: always
    ports:
      - 6379:6379
  webappbackend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - /home/app/node_modules
      - ./back-end:/home/app
  webappfrontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - /home/app/node_modules
      - ./front-end:/home/app
